# site settings

title: thureindev
description: About me, CV and conact links are all here
taglong: Code in MERN stack. Learning Python.
tagshort: Web Developer
url: https://thureindev.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/thureindev/about

# author settings

author:
  name: thureindev
  email: thureindev@outlook.com
photo: /assets/avatar.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
